//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoSchoolProMVC.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int AptId { get; set; }
        public string Location { get; set; }
        public string RentRange { get; set; }
        public string BedsxBath { get; set; }
        public Nullable<bool> Parking { get; set; }
        public string Preferences { get; set; }
        public Nullable<int> AUserId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
