//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoSchoolProMVC.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeachVoice
    {
        public int BeachVoiceId { get; set; }
        public string Question { get; set; }
        public string QuestionCategory { get; set; }
        public string Answer { get; set; }
        public Nullable<int> BUserId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
