//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoSchoolProMVC.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSProDbEntities : DbContext
    {
        public GSProDbEntities()
            : base("name=GSProDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirportPckUp> AirportPckUps { get; set; }
        public virtual DbSet<Apartment> Apartments { get; set; }
        public virtual DbSet<BeachVoice> BeachVoices { get; set; }
        public virtual DbSet<GoTour> GoTours { get; set; }
        public virtual DbSet<KnowBeach> KnowBeaches { get; set; }
        public virtual DbSet<Roommate> Roommates { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
