//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoSchoolProMVC.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowBeach
    {
        public int KnowBeachNo { get; set; }
        public string CourseNumber { get; set; }
        public string CourseName { get; set; }
        public string Professor { get; set; }
        public string Semester { get; set; }
        public Nullable<int> CourseLoadFactor { get; set; }
        public Nullable<int> CourseRating { get; set; }
        public Nullable<int> ProfessorRating { get; set; }
        public Nullable<int> KUserId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
