//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoSchoolProMVC.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roommate
    {
        public int RmId { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string Program { get; set; }
        public string Rent { get; set; }
        public string Distance { get; set; }
        public string Sharing { get; set; }
        public string Pets { get; set; }
        public string Socially { get; set; }
        public string Cleanliness { get; set; }
        public string Smoking { get; set; }
        public string Working { get; set; }
        public Nullable<int> RUserId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
